Description of grNeighborNodes
Home > matGeom > graphs > grNeighborNodes.m
grNeighborNodes
PURPOSE
GRNEIGHBORNODES Find adjacent nodes of a given node
SYNOPSIS
function nodes2 = grNeighborNodes(edges, node)
DESCRIPTION
GRNEIGHBORNODES Find adjacent nodes of a given node
   NEIGHS = grNeighborNodes(EDGES, NODE)
   EDGES: the complete edges list
   NODE: index of the node
   NEIGHS: the nodes adjacent to the given node.
   NODE can also be a vector of node indices, in this case the result is
   the set of neighbors of any input node.
   -----
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 16/08/2004.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
grClose GRCLOSE Morphological closing on graph
grDilate GRDILATE Morphological dilation on graph
grErode GRERODE Morphological erosion on graph
grFindGeodesicPath GRFINDGEODESICPATH Find a geodesic path between two nodes in the graph
grFindMaximalLengthPath GRFINDMAXIMALLENGTHPATH Find a path that maximizes sum of edge weights
grLabel GRLABEL Associate a label to each connected component of the graph
grMean GRMEAN Compute mean from neihgbours
grMedian GRMEDIAN Compute median from neihgbours
grMergeNodesMedian GRMERGENODESMEDIAN Replace several nodes by their median coordinate
grOpen GROPEN Morphological opening on graph
grRemoveNode GRREMOVENODE Remove a node in a graph
grRemoveNodes GRREMOVENODES Remove several nodes in a graph
grSimplifyBranches_old GRSIMPLIFYBRANCHES_OLD Replace branches of a graph by single edges
SOURCE CODE
function nodes2 = grNeighborNodes(edges, node)
%GRNEIGHBORNODES Find adjacent nodes of a given node
%
%   NEIGHS = grNeighborNodes(EDGES, NODE)
%   EDGES: the complete edges list
%   NODE: index of the node
%   NEIGHS: the nodes adjacent to the given node.
%
%   NODE can also be a vector of node indices, in this case the result is
%   the set of neighbors of any input node.
%
%   -----
%
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 16/08/2004.
%
%   HISTORY
%   10/02/2004 documentation
%   13/07/2004 faster algorithm
%   03/10/2007 can specify several input nodes
[i, j] = find(ismember(edges, node)); %#ok<NASGU>
nodes2 = edges(i,1:2);
nodes2 = unique(nodes2(:));
nodes2 = sort(nodes2(~ismember(nodes2, node)));