Description of deg2rad
Home > matGeom > geom2d > deg2rad.m
deg2rad
PURPOSE
DEG2RAD Convert angle from degrees to radians
SYNOPSIS
function rad = deg2rad(deg)
DESCRIPTION
DEG2RAD Convert angle from degrees to radians
   Usage:
   R = deg2rad(D)
   convert an angle in degrees to an angle in radians.
   Example
   deg2rad(180)    % gives pi
   ans =
       3.1416
   deg2rad(60)     % gives pi/3
   ans =
       1.0472
   See Also
   angles2d, rad2deg
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 09/12/2004.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
circleArcToPolyline CIRCLEARCTOPOLYLINE Convert a circle arc into a series of points
drawCircleArc DRAWCIRCLEARC Draw a circle arc on the current axis
drawEllipseArc DRAWELLIPSEARC Draw an ellipse arc on the current axis
drawParabola DRAWPARABOLA Draw a parabola on the current axis
isPointInEllipse ISPOINTINELLIPSE Check if a point is located inside a given ellipse
SOURCE CODE
function rad = deg2rad(deg)
%DEG2RAD Convert angle from degrees to radians
%
%   Usage:
%   R = deg2rad(D)
%   convert an angle in degrees to an angle in radians.
%
%   Example
%   deg2rad(180)    % gives pi
%   ans =
%       3.1416
%   deg2rad(60)     % gives pi/3
%   ans =
%       1.0472
%
%   See Also
%   angles2d, rad2deg
%
%   ---------
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 09/12/2004.
%
rad = deg*pi/180;