Description of isAxisHandle
Home > matGeom > geom2d > isAxisHandle.m
isAxisHandle
PURPOSE
ISAXISHANDLE Check if the input corresponds to a valid axis hanfle
SYNOPSIS
function b = isAxisHandle(arg)
DESCRIPTION
ISAXISHANDLE Check if the input corresponds to a valid axis hanfle
   B = isAxisHandle(VAR)
   If the value of VAR is scalar, corresponds to a valid matlab handle,
   and has type equal to 'axis', then returns TRUE. Otherwise, returns
   false.
   This function is used to check if first argument of drawing functions
   corresponds to data or to axis handle to draw in.
   Example
     isAxisHandle(gca)
     ans =
         1
   See also
   drawPoint, drawLine, drawEdge
 ------
 Author: David Legland
 e-mail: david.legland@grignon.inra.fr
 Created: 2012-09-21,    using Matlab 7.9.0.529 (R2009b)
 Copyright 2012 INRA - Cepia Software Platform.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
drawBezierCurve DRAWBEZIERCURVE Draw a cubic bezier curve defined by 4 control points
drawBox DRAWBOX Draw a box defined by coordinate extents
drawCenteredEdge DRAWCENTEREDEDGE Draw an edge centered on a point
drawCircle DRAWCIRCLE Draw a circle on the current axis
drawCircleArc DRAWCIRCLEARC Draw a circle arc on the current axis
drawEdge DRAWEDGE Draw an edge given by 2 points
drawEllipse DRAWELLIPSE Draw an ellipse on the current axis
drawEllipseArc DRAWELLIPSEARC Draw an ellipse arc on the current axis
drawLine DRAWLINE Draw a straight line clipped by the current axis
drawOrientedBox DRAWORIENTEDBOX Draw centered oriented rectangle
drawParabola DRAWPARABOLA Draw a parabola on the current axis
drawPoint DRAWPOINT Draw the point on the axis.
drawRay DRAWRAY Draw a ray on the current axis
drawRect DRAWRECT Draw rectangle on the current axis
drawPolygon DRAWPOLYGON Draw a polygon specified by a list of points
drawPolyline DRAWPOLYLINE Draw a polyline specified by a list of points
drawVertices DRAWVERTICES Draw the vertices of a polygon or polyline
SOURCE CODE
function b = isAxisHandle(arg)
%ISAXISHANDLE Check if the input corresponds to a valid axis hanfle
%
%   B = isAxisHandle(VAR)
%   If the value of VAR is scalar, corresponds to a valid matlab handle,
%   and has type equal to 'axis', then returns TRUE. Otherwise, returns
%   false.
%   This function is used to check if first argument of drawing functions
%   corresponds to data or to axis handle to draw in.
%
%   Example
%     isAxisHandle(gca)
%     ans =
%         1
%
%   See also
%   drawPoint, drawLine, drawEdge
%
% ------
% Author: David Legland
% e-mail: david.legland@grignon.inra.fr
% Created: 2012-09-21,    using Matlab 7.9.0.529 (R2009b)
% Copyright 2012 INRA - Cepia Software Platform.
b = isscalar(arg) && ishandle(arg) && strcmp(get(arg, 'type'), 'axes');