% in 2D and 3D
%   params{1} SE(n) is the center of rotation (WRT from-object center)
%   params{2} SE(n) is the offset from the center to the moving part at state=0
%   params{3} R     is the screw pitch/lead (meters per radian)
%   state     R     is the angle around the circle / length of extension

function [x, Dr, Dt] = forward_screw(p, state)
    if iscell(p)
        params = p;
    else
        [params, ct, cr, ~, rr] = unpack_screw(p);
    end
    center = params{1};
    radius = params{2};
    pitch = params{3};
    
    theta = state;
    ext = state*pitch;
    
    n = size(center,1)-1;
    x = radius * R(theta*eye(1,n*(n-1)/2)) * T([0 0 ext]) * center;
    
    if nargout > 1
        if iscell(p)
            [ct, cr] = extract_SE(center);
            [~, rr] = extract_SE(radius);
        end

        ccr = cos(cr);
        scr = sin(cr);
        crr = cos(rr);
        srr = sin(rr);
        cs = cos(state);
        ss = sin(state);
        s = state;
Dr = [ 0, 0, 0,   (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) + (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))),   ccr(1)*ccr(3)*scr(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) + ccr(3)*scr(1)*scr(2)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - ccr(2)*ccr(3)*crr(1)*srr(2), (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) + crr(1)*scr(2)*scr(3)*srr(2), 0, 0, 0, (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) + ccr(3)*scr(2)*srr(1)*srr(2), (crr(1)*crr(3)*srr(2)*ss + crr(1)*cs*srr(2)*srr(3))*(ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1)) + (crr(1)*crr(3)*cs*srr(2) - crr(1)*srr(2)*srr(3)*ss)*(scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3)) - ccr(3)*crr(1)*crr(2)*scr(2),   (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) + (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))), 0,   (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) + (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)))
 0, 0, 0, - (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))), - ccr(1)*ccr(3)*scr(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - ccr(3)*scr(1)*scr(2)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - ccr(2)*ccr(3)*srr(1)*srr(2), (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) + scr(2)*scr(3)*srr(1)*srr(2), 0, 0, 0, (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) - (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - ccr(3)*crr(1)*scr(2)*srr(2), (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(crr(3)*srr(1)*srr(2)*ss + cs*srr(1)*srr(2)*srr(3)) + (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(crr(3)*cs*srr(1)*srr(2) - srr(1)*srr(2)*srr(3)*ss) - ccr(3)*crr(2)*scr(2)*srr(1), - (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))), 0, - (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)))
 0, 0, 0,                                                                                                                               (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) + (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)),                                                                                                                                        ccr(2)*ccr(3)*crr(2) + ccr(1)*ccr(3)*scr(2)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) + ccr(3)*scr(1)*scr(2)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)),                                                                                                                                      (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) - crr(2)*scr(2)*scr(3), 0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                 0,                                              (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(crr(2)*srr(3)*ss - crr(2)*crr(3)*cs) - (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(crr(2)*crr(3)*ss + crr(2)*cs*srr(3)) - ccr(3)*scr(2)*srr(2),                                                                                                                               (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) + (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)), 0,                                                                                                                               (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) + (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3))
 0, 0, 0,   (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) + (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))),   ccr(2)*crr(1)*scr(3)*srr(2) - scr(1)*scr(2)*scr(3)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - ccr(1)*scr(2)*scr(3)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))), (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) + ccr(3)*crr(1)*scr(2)*srr(2), 0, 0, 0, (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - scr(2)*scr(3)*srr(1)*srr(2), (crr(1)*crr(3)*srr(2)*ss + crr(1)*cs*srr(2)*srr(3))*(ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3)) + (crr(1)*crr(3)*cs*srr(2) - crr(1)*srr(2)*srr(3)*ss)*(ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3)) + crr(1)*crr(2)*scr(2)*scr(3),   (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) + (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))), 0,   (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) + (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)))
 0, 0, 0, - (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))),   ccr(1)*scr(2)*scr(3)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) + scr(1)*scr(2)*scr(3)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) + ccr(2)*scr(3)*srr(1)*srr(2), (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) + ccr(3)*scr(2)*srr(1)*srr(2), 0, 0, 0, (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) + crr(1)*scr(2)*scr(3)*srr(2), (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(crr(3)*cs*srr(1)*srr(2) - srr(1)*srr(2)*srr(3)*ss) + (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(crr(3)*srr(1)*srr(2)*ss + cs*srr(1)*srr(2)*srr(3)) + crr(2)*scr(2)*scr(3)*srr(1), - (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))), 0, - (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)))
 0, 0, 0,                                                                                                                               (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) + (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)),                                                                                                                                      - ccr(2)*crr(2)*scr(3) - ccr(1)*scr(2)*scr(3)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) - scr(1)*scr(2)*scr(3)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)),                                                                                                                                      (ccr(1)*scr(3) + ccr(2)*ccr(3)*scr(1))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) - (scr(1)*scr(3) - ccr(1)*ccr(2)*ccr(3))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) - ccr(3)*crr(2)*scr(2), 0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                 0,                                              (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(crr(2)*srr(3)*ss - crr(2)*crr(3)*cs) - (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(crr(2)*crr(3)*ss + crr(2)*cs*srr(3)) + scr(2)*scr(3)*srr(2),                                                                                                                               (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) + (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)), 0,                                                                                                                               (ccr(3)*scr(1) + ccr(1)*ccr(2)*scr(3))*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) + (ccr(1)*ccr(3) - ccr(2)*scr(1)*scr(3))*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2))
 0, 0, 0,                                                                 ccr(1)*scr(2)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - scr(1)*scr(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))),                              ccr(1)*ccr(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) + ccr(2)*scr(1)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) + crr(1)*scr(2)*srr(2),                                                                                                                                                                                                                                                                                                                                                                                 0, 0, 0, 0,                                                                        ccr(1)*scr(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) + scr(1)*scr(2)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) + ccr(2)*srr(1)*srr(2),                                                                        ccr(1)*scr(2)*(crr(1)*crr(3)*cs*srr(2) - crr(1)*srr(2)*srr(3)*ss) - scr(1)*scr(2)*(crr(1)*crr(3)*srr(2)*ss + crr(1)*cs*srr(2)*srr(3)) - ccr(2)*crr(1)*crr(2),                                                                 ccr(1)*scr(2)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - scr(1)*scr(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))), 0,                                                                 ccr(1)*scr(2)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - scr(1)*scr(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)))
 0, 0, 0,                                                                 scr(1)*scr(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - ccr(1)*scr(2)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))),                              scr(2)*srr(1)*srr(2) - ccr(1)*ccr(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - ccr(2)*scr(1)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))),                                                                                                                                                                                                                                                                                                                                                                                 0, 0, 0, 0,                                                                        ccr(1)*scr(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) + scr(1)*scr(2)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - ccr(2)*crr(1)*srr(2),                                                                        ccr(1)*scr(2)*(crr(3)*cs*srr(1)*srr(2) - srr(1)*srr(2)*srr(3)*ss) - scr(1)*scr(2)*(crr(3)*srr(1)*srr(2)*ss + cs*srr(1)*srr(2)*srr(3)) - ccr(2)*crr(2)*srr(1),                                                                 scr(1)*scr(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - ccr(1)*scr(2)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))), 0,                                                                 scr(1)*scr(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - ccr(1)*scr(2)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)))
 0, 0, 0,                                                                                                                                                                                             ccr(1)*scr(2)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) - scr(1)*scr(2)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)),                                                                                                                                                                   ccr(1)*ccr(2)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) - crr(2)*scr(2) + ccr(2)*scr(1)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)),                                                                                                                                                                                                                                                                                                                                                                                 0, 0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                 0,                                                                                                                     ccr(1)*scr(2)*(crr(2)*srr(3)*ss - crr(2)*crr(3)*cs) - ccr(2)*srr(2) + scr(1)*scr(2)*(crr(2)*crr(3)*ss + crr(2)*cs*srr(3)),                                                                                                                                                                                             ccr(1)*scr(2)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) - scr(1)*scr(2)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)), 0,                                                                                                                                                                                             ccr(1)*scr(2)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) - scr(1)*scr(2)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2))];

Dt = [ - cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) - ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)), ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) - cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)), -crr(1)*srr(2), 0, 0, 0, 1, 1, 0,   ct(3)*srr(1)*srr(2) - ct(2)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - ct(1)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) + pitch*s*srr(1)*srr(2), ct(2)*(crr(1)*crr(3)*srr(2)*ss + crr(1)*cs*srr(2)*srr(3)) - ct(1)*(crr(1)*crr(3)*cs*srr(2) - crr(1)*srr(2)*srr(3)*ss) - ct(3)*crr(1)*crr(2) - pitch*s*crr(1)*crr(2), ct(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) - ct(1)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))), -s*crr(1)*srr(2), ct(2)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) - ct(1)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - pitch*crr(1)*srr(2)
   cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)), cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)), -srr(1)*srr(2), 0, 0, 0, 1, 1, 0, - ct(1)*(cs*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3)) + ss*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3))) - ct(2)*(cs*(crr(3)*srr(1) + crr(1)*crr(2)*srr(3)) - ss*(srr(1)*srr(3) - crr(1)*crr(2)*crr(3))) - ct(3)*crr(1)*srr(2) - pitch*s*crr(1)*srr(2), ct(2)*(crr(3)*srr(1)*srr(2)*ss + cs*srr(1)*srr(2)*srr(3)) - ct(1)*(crr(3)*cs*srr(1)*srr(2) - srr(1)*srr(2)*srr(3)*ss) - ct(3)*crr(2)*srr(1) - pitch*s*crr(2)*srr(1), ct(1)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - ct(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))), -s*srr(1)*srr(2), ct(1)*(cs*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3)) - ss*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1))) - ct(2)*(cs*(crr(1)*srr(3) + crr(2)*crr(3)*srr(1)) + ss*(crr(1)*crr(3) - crr(2)*srr(1)*srr(3))) - pitch*srr(1)*srr(2)
                                                                 crr(3)*cs*srr(2) - srr(2)*srr(3)*ss,                                                             - crr(3)*srr(2)*ss - cs*srr(2)*srr(3),           crr(2), 0, 0, 0, 0, 0, 1,                                                                                                                                                                                                                                                                                                   0,                                                     - ct(1)*(crr(2)*srr(3)*ss - crr(2)*crr(3)*cs) - ct(2)*(crr(2)*crr(3)*ss + crr(2)*cs*srr(3)) - ct(3)*srr(2) - pitch*s*srr(2),                                                                                                                             ct(2)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) - ct(1)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)),           s*crr(2),                                                                                                                                      ct(2)*(srr(2)*srr(3)*ss - crr(3)*cs*srr(2)) - ct(1)*(crr(3)*srr(2)*ss + cs*srr(2)*srr(3)) + pitch*crr(2)];

    end
end
