Description of normalizeVector3d
Home > matGeom > geom3d > normalizeVector3d.m
normalizeVector3d
PURPOSE
NORMALIZEVECTOR3D Normalize a 3D vector to have norm equal to 1
SYNOPSIS
function vn = normalizeVector3d(v)
DESCRIPTION
NORMALIZEVECTOR3D Normalize a 3D vector to have norm equal to 1
   V2 = normalizeVector3d(V);
   Returns the normalization of vector V, such that ||V|| = 1. Vector V is
   given as a row vector.
   If V is a N-by-3 array, normalization is performed for each row of the
   input array.
   See also:
   vectors3d, vectorNorm3d
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 29/11/2004.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
anglePoints3d ANGLEPOINTS3D Compute angle between three 3D points
createPlane CREATEPLANE Create a plane in parametrized form
createRotation3dLineAngle CREATEROTATION3DLINEANGLE Create rotation around a line by an angle theta
distancePointPlane DISTANCEPOINTPLANE Signed distance betwen 3D point and plane
drawSphericalTriangle DRAWSPHERICALTRIANGLE Draw a triangle on a sphere
fillSphericalTriangle FILLSPHERICALTRIANGLE Fill a triangle on a sphere
intersectPlanes INTERSECTPLANES Return intersection line between 2 planes in space
normalizePlane NORMALIZEPLANE Normalize parametric representation of a plane
parallelPlane PARALLELPLANE Parallel to a plane through a point or at a given distance
sphericalAngle SPHERICALANGLE Compute angle between points on the sphere
faceNormal FACENORMAL Compute normal vector of faces in a 3D mesh
intersectLineMesh3d INTERSECTLINEMESH3D Intersection points of a 3D line with a mesh
meshSurfaceArea MESHSURFACEAREA Surface area of a polyhedral mesh
vertexNormal VERTEXNORMAL Compute normals to a mesh vertices
SOURCE CODE
function vn = normalizeVector3d(v)
%NORMALIZEVECTOR3D Normalize a 3D vector to have norm equal to 1
%
%   V2 = normalizeVector3d(V);
%   Returns the normalization of vector V, such that ||V|| = 1. Vector V is
%   given as a row vector.
%
%   If V is a N-by-3 array, normalization is performed for each row of the
%   input array.
%
%   See also:
%   vectors3d, vectorNorm3d
%
%   ---------
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 29/11/2004.
%
% HISTORY
% 2005-11-30 correct a bug
% 2009-06-19 rename as normalizeVector3d
% 2010-11-16 use bsxfun (Thanks to Sven Holcombe)
vn   = bsxfun(@rdivide, v, sqrt(sum(v.^2, 2)));