Description of planePosition
Home > matGeom > geom3d > planePosition.m
planePosition
PURPOSE
PLANEPOSITION Compute position of a point on a plane
SYNOPSIS
function pos = planePosition(point, plane)
DESCRIPTION
PLANEPOSITION Compute position of a point on a plane
   PT2 = planePosition(POINT, PLANE)
   POINT has format [X Y Z], and plane has format
   [X0 Y0 Z0  DX1 DY1 DZ1  DX2 DY2 DZ2], where :
   - (X0, Y0, Z0) is a point belonging to the plane
   - (DX1, DY1, DZ1) is a first direction vector
   - (DX2, DY2, DZ2) is a second direction vector
   Result PT2 has the form [XP YP], with [XP YP] coordinate of the point
   in the coordinate system of the plane.
   CAUTION:
   WORKS ONLY FOR PLANES WITH ORTHOGONAL DIRECTION VECTORS
   See also:
   planes3d, points3d, planePoint
   ---------
   author : David Legland
   INRA - TPV URPOI - BIA IMASTE
   created the 21/02/2005.
CROSS-REFERENCE INFORMATION
This function calls:
vectorNorm3d VECTORNORM3D Norm of a 3D vector or of set of 3D vectors
This function is called by:
angleSort3d ANGLESORT3D Sort 3D coplanar points according to their angles in plane
circle3dPosition CIRCLE3DPOSITION Return the angular position of a point on a 3D circle
fillSphericalTriangle FILLSPHERICALTRIANGLE Fill a triangle on a sphere
intersectLinePolygon3d INTERSECTLINEPOLYGON3D Intersection point of a 3D line and a 3D polygon
polygonCentroid3d POLYGONCENTROID3D Centroid (or center of mass) of a polygon
sphericalAngle SPHERICALANGLE Compute angle between points on the sphere
SOURCE CODE
function pos = planePosition(point, plane)
%PLANEPOSITION Compute position of a point on a plane
%
%   PT2 = planePosition(POINT, PLANE)
%   POINT has format [X Y Z], and plane has format
%   [X0 Y0 Z0  DX1 DY1 DZ1  DX2 DY2 DZ2], where :
%   - (X0, Y0, Z0) is a point belonging to the plane
%   - (DX1, DY1, DZ1) is a first direction vector
%   - (DX2, DY2, DZ2) is a second direction vector
%
%   Result PT2 has the form [XP YP], with [XP YP] coordinate of the point
%   in the coordinate system of the plane.
%
%
%   CAUTION:
%   WORKS ONLY FOR PLANES WITH ORTHOGONAL DIRECTION VECTORS
%
%   See also:
%   planes3d, points3d, planePoint
%
%   ---------
%   author : David Legland
%   INRA - TPV URPOI - BIA IMASTE
%   created the 21/02/2005.
%
%   HISTORY
%   24/11/2005 add support for multiple input
% unify size of data
if size(point, 1)~=size(plane, 1)
    if size(point, 1)==1
        point = repmat(point, [size(plane, 1) 1]);
    elseif size(plane, 1)==1
        plane = repmat(plane, [size(point, 1) 1]);
    else
        error('point and plane do not have the same dimension');
    end
end
p0 = plane(:, 1:3);
d1 = plane(:, 4:6);
d2 = plane(:, 7:9);
s = dot(point-p0, d1, 2) ./ vectorNorm3d(d1);
t = dot(point-p0, d2, 2) ./ vectorNorm3d(d2);
pos = [s t];