Description of polynomialDerivate
Home > matGeom > polynomialCurves2d > polynomialDerivate.m
polynomialDerivate
PURPOSE
POLYNOMIALDERIVATE Derivate a polynomial
SYNOPSIS
function deriv = polynomialDerivate(poly)
DESCRIPTION
POLYNOMIALDERIVATE Derivate a polynomial
   DERIV = polynomialDERIVATE(POLY)
   POLY is a row vector of [n+1] coefficients, in the form:
       [a0 a1 a2 ... an]
   DERIV has the same format, with length n:
       [a1 a2*2 ... an*n]
   Example
   T = polynomialDerivate([2 3 4])
   returns:
   T = [3 8]
   See also
   polynomialCurves2d
 ------
 Author: David Legland
 e-mail: david.legland@grignon.inra.fr
 Created: 2007-02-23
 Copyright 2007 INRA - BIA PV Nantes - MIAJ Jouy-en-Josas.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
polynomialCurveCentroid POLYNOMIALCURVECENTROID Compute the centroid of a polynomial curve
polynomialCurveCurvature POLYNOMIALCURVECURVATURE Compute the local curvature of a polynomial curve
polynomialCurveCurvatures POLYNOMIALCURVECURVATURES Compute curvatures of a polynomial revolution surface
polynomialCurveDerivative POLYNOMIALCURVEDERIVATIVE Compute derivative vector of a polynomial curve
polynomialCurveLength POLYNOMIALCURVELENGTH Compute the length of a polynomial curve
polynomialCurvePosition POLYNOMIALCURVEPOSITION Compute position on a curve for a given length
SOURCE CODE
function deriv = polynomialDerivate(poly)
%POLYNOMIALDERIVATE Derivate a polynomial
%
%   DERIV = polynomialDERIVATE(POLY)
%   POLY is a row vector of [n+1] coefficients, in the form:
%       [a0 a1 a2 ... an]
%   DERIV has the same format, with length n:
%       [a1 a2*2 ... an*n]
%
%
%   Example
%   T = polynomialDerivate([2 3 4])
%   returns:
%   T = [3 8]
%
%   See also
%   polynomialCurves2d
%
% ------
% Author: David Legland
% e-mail: david.legland@grignon.inra.fr
% Created: 2007-02-23
% Copyright 2007 INRA - BIA PV Nantes - MIAJ Jouy-en-Josas.
% create the derivation matrices
matrix = diag(0:length(poly)-1);
% compute coefficients of first derivative polynomials
deriv = circshift(poly*matrix, [0 -1]);